name             'audit-osx'
maintainer       'Paul Welch'
maintainer_email 'paul@pwelch.net'
license          'MIT'
description      'Audits OS X with Chef-Audit'
long_description 'Audits OS X with Chef-Audit'
version          '0.1.0'

supports         'mac_os_x'
supports         'mac_os_x_server'
